version: "3.7"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true # if not build app.
    ports: 
      - 8001:8001
    depends_on: 
      - mongo
    environment:
      RUST_BACKTRACE: full
    volumes:
      - ./:/code

  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root  
      MONGO_INITDB_DATABASE: mongo
    volumes: 
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root    

volumes: 
  mongodb-data: 